# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 09:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 9, 58, 56, 90500, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
